### ISSUE TITLE
Codes?

### ISSUE THREAD

**Issue by sidbala2310** [zhangjinyangnwpu/HSI_Classification#1]
Are the codes for the models not pushed?

**Comment by zhangjinyangnwpu** [comment]
I will release the code later when I orginize them well, sorry for that,  a little busy recently

**Comment by WaterVcc** [comment]
I want to see your paper which uses this code. my email is 1756784389@qq.com

**Comment by zhangjinyangnwpu** [comment]
There are no references, and I designed the classifier by myself, here I
just show a demo that how to use 1D, 2D or 3D convolution.

WaterVcc <notifications@github.com> 于2018年9月11日周二 下午8:27写道：
