### ISSUE TITLE
Hi ,can you tell me what kind of color do you represent after classification?

### ISSUE THREAD

**Issue by hwd-996** [zhangjinyangnwpu/HSI_Classification#11]

**Comment by ZHUYMGeo** [comment]
cmap="jet"   I think

**Comment by zhangjinyangnwpu** [comment]
you can find the specific category in follow link, the color map generated by this repository not precisely controlled, just set with plt.pcolor(de_map, cmap='jet')
https://www.ehu.eus/ccwintco/index.php?title=Hyperspectral_Remote_Sensing_Scenes
