### ISSUE TITLE
 No module named 'model'

### ISSUE THREAD

**Issue by ZHUYMGeo** [zhangjinyangnwpu/HSI_Classification#12]
HI  thank you for your share
I come up this question:
---------Q----------
    from model import Model
ModuleNotFoundError: No module named 'model'

Can you provide model file?

**Comment by dadong1999** [comment]
the same problem

**Comment by decentjoker** [comment]
the same problem,did u solved it?

**Comment by LifeIsBright-heihei** [comment]
the same problem

**Comment by zhangjinyangnwpu** [comment]
added model.py to folder, sorry for writing model.* in .gitignore
