### ISSUE TITLE
what was 'info.mat' in main.py?

### ISSUE THREAD

**Issue by zhshining** [zhangjinyangnwpu/HSI_Classification#6]
hi, I don't see what was 'info.mat', can you tell me how to get it?

**Comment by zhangjinyangnwpu** [comment]
Info.mat save some configuration of the dataset, it can be generated in data_loader.py, when you define a object of dataset with the class in data_loader.py, when you use the dataset().readdata() function, it can be generated. Hope can help you. So the key point is you must use the right path and dataset of HSI in main function.

**Comment by zhshining** [comment]
You mean I should change the dataset's name and the num  of classes when I use data_loader.py?
I run the data_loader, but it couldn't get a data, so I download dataset by myself? What should I change 'info.mat' if I download dataset by myself.
